### ISSUE TITLE
email (sms?) subscriptions for events

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#174]
We should consider an option for the edesks or other MSFers to “subscribe” to an event.  Being subscribed means they get an email if information (latest notification) is updated on the event.  Those not subscribed will still get the updates that are manually shared by the operator.  I’m not sure about this one, but we can discuss

**Comment by matthewberryman** [comment]
@mehrdadgit let's discuss this next week

**Comment by mehrdadgit** [comment]
Sorry I just saw your last comment above @matthewberryman ; I can start this; I think we have to look into how to we can obtain user id from aws cognito and work with that in the database ...

**Comment by matthewberryman** [comment]
@mehrdadgit please hold on this as we're looking to move to active directory for auth

**Comment by matthewberryman** [comment]
1. @mehrdadgit to adjust wording to "follow event by email" instead of "subscribe" (work in issues/174 branch).
2. We already have the ability to unsubscribe from notification emails. @mehrdadgit to add a button "unfollow this event" (work in issues/174 branch).
3. This is problematic for two reasons (a) Allowing operators to directly subscribe others doesn't follow [AWS best practice](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/tips-and-best-practices.html) which suggests the use of double opt in to avoid emails being seen (and reported) as spam. (b) We would have to re-write the server code to accomodate this new (sub)feature requested. I had another look at the platform we're using for the share buttons, and for the share event by email one, it is now possible to set the body of the email to some text that could read `To subscribe to (name of event), click on "follow event by email" on the event page: (link to event page)`, and then the operator can select addresses from the MSF address book in the to field of the email. This would then satisfies the double opt in best practice.
4. @mehrdadgit to implement this in issues/174 branch. UI side: on event edit, need to have a button "save & update email subscribers" separate to existing "save", with only the updated fields passed through to email, noting template will need adjusting. Just noting that email is not necessarily end to end encrypted, so @LucieGueuning to email existing and new operators to let them know, once this feature is in prod.
5. @LucieGueuning to file this in 'my event' issue with @qclin for implementation in phase 2c.

**Comment by LucieGueuning** [comment]
1. please follow the wording up there 'Follow this event by email' instead of 'subscribers'. Keep the 'subscribe' button!
2. write 'unsubscribe' next to the 'subscribe' button
3. I won't send an email for that. It is not necessary. 
4. well noted. I believe @qclin is keeping track of that. Thanks!

**Comment by matthewberryman** [comment]
1&2. Oh, right, I was getting mixed up between text for that row and the button text. @mehrdadgit Lucie is correct, change "Subscribers:" on the left to "Follow this event by email:" and add unsubscribe button simply reading unsubscribe.
3. Ok.
4. I'm just worried about security especially for conflict-related events. To discuss in next meeting.
5. Ok.

**Comment by matthewberryman** [comment]
* Defer on putting event update details in email for now, just keep as name of event and link.
* @LucieGueuning to check about options for double opt in (to consider email button for event sharing since we can change email now to read something like 'The (name of event) has been added to REACH and you can view and subscribe to it at (link to event)'

**Comment by LucieGueuning** [comment]
as per Remi: 
- putting people from your organisation in cc is a bad practice? This is what we aim to do by putting a list of people. once hitting the button 'shared updates to subscribers', it will open an email drafted already and the recipients will in there already. Operators will need to send the email manually. 
- no email sent automatically from REACH


steps: 
1. input the list of people you want to notify for this particular event
2. press a button to share updates/changes made to the event
3. it opens a drafted email with recipients (as of people that you input in 1.)

**Comment by matthewberryman** [comment]
@LucieGueuning As discussed on our call, the bad practice would be subscribing people without confirmation. If you're sending a sharing email to a list of people then use bcc in email... With the current email sharing button we cannot pre-fill to/cc/bcc. We could separately (with additional work) generate a "mailto:" hyperlink although as discussed then we'd be duplicating functionality in REACH that is already present in the mail client (to select people from MSF address book and add them to to/cc/bcc fields as desired).

**Comment by LucieGueuning** [comment]
from MB: 
would that all be from the event description? Per our previous call I need a list of fields to use and generic surrounding text, noting:
* The email body is then mostly up to what operators put into the field(s).
* The more fields we select, the more likely it is that the information is sensitive, and emails are not necessarily end-to-end encrypted.

**Comment by LucieGueuning** [comment]
requirements refined (as per last meeting). To be confirmed by Ken, Fiona, Natasha (cf. email sent)

Explanation: 
- people won't follow the event by themselves at the moment.
- this feature is to make the operator/user's life easier (cf. Ken, Fiona, Natasha)

Process: (for operator display ONLY)
- Add a button below the 'subscribe' one : '**add subscribers**'. This brings you to the function of typing a name and the address book find the email address (as per private function in contact card)
- add a button below the 'Follow this event by email' one: '**Send an update**'. By pressing this button, it opens a outlook window with people subscribed or that operators subscribed with the following information: 

**Subject**: 
[Name of the event] - updates on REACH

**Body**: 
Hi all, 

This is to kindly inform you that there has been updates on the [name of the event] to be shared with you. Please read them below: 
- ...
- ...

For more detailed updates, please find them here [hyperlink to event specific]. 

If you have any questions, please do not hesitate to contact me at any time. 

Best, 
[do not forget your name] (in red and bold)

**Comment by matthewberryman** [comment]
@mehrdadgit would you please take a look at https://github.com/MSFREACH/msf-reach/commit/ebf0132726232f996f270a9a48c155d7f9f6b572 on issues/174 branch (and just noting I corrected the button wording). Things to fix:
* Button placement for this button, also the generic one for sharing email should appear after / as part of fixing #667 (which should then have a message about ability to subscribe, as a double opt in, rather than subscribing someone without permission).
* The href attribute for the new button isn't getting updated. I suspect my code in https://github.com/MSFREACH/msf-reach/commit/ebf0132726232f996f270a9a48c155d7f9f6b572 is good just in the wrong place for vue (my bad)

**Comment by mehrdadgit** [comment]
Done.

**Comment by LucieGueuning** [comment]
Feedback: 
- Still not able, as operators, to add subscribers. Add a button below the 'subscribe' one : 'add subscribers'. This brings you to the function of typing a name and the address book find the email address (as per private function in contact card)
- Can we have the name of the person instead of his email once the person subscribe or is made as subscriber to the event? 
- All subscribers should be in the To: and not in BBC. Therefore, it is not needed to re-send the email to the one sending the updates. 
- In the body of email. [name of event] needs to be replace by the name of event
- In the body email, signature needs to be the first name of the one pressing the button 'send an update'. Is it the case o is it as default ' Lucie Gueuning'? 
- In the body email, here should be the hyperlink to the event and not the link visible. 

- BUG: Once I subscribe and unsubscribe it removes even the other subscribers on the display, but still in the database as there remain in the recipients for the email to be sent. 
Videos sent by email.

**Comment by matthewberryman** [comment]
> Still not able, as operators, to add subscribers. Add a button below the 'subscribe' one : 'add subscribers'. This brings you to the function of typing a name and the address book find the email address (as per private function in contact card)

As discussed this is still a work in progress.

> Can we have the name of the person instead of his email once the person subscribe or is made as subscriber to the event?

I'll give this a spin next week — it looks straightforward to capture this but I need to test it.

> All subscribers should be in the To: and not in BBC. Therefore, it is not needed to re-send the email to the one sending the updates.

I don't think this is a good idea to add people to the To field:
* If someone hits reply all it can end up being spammy
* Indeed some spam filters will look at the number of recipients in the To: field when considering when to send an email to junk
* It invites an email conversation about the event whereas we want to guide people to put information into MSF REACH.
* There is malware that automatically sends out to email addresses based on the to field.

As an alternative to putting the sender in the To field I could set up a catch all email address that just silently ignores emails sent.

> In the body of email. [name of event] needs to be replace by the name of event

Fix going in now in 00c6831d2ee643adf402b64b4d3cbe5031fe6756

> In the body email, signature needs to be the first name of the one pressing the button 'send an update'. Is it the case o is it as default ' Lucie Gueuning'?

This is automatically populated with the full name dynamically, so you see your name when you send it, but when I log in with the REACH TEST account I get this:
<img width="113" alt="screenshot 2018-11-02 08 29 47" src="https://user-images.githubusercontent.com/2288238/47881205-9959ac00-de79-11e8-97a2-f7eff3123d21.png">

I suggest leaving it as full name:
* It's a (semi)formal email so full name is more appropriate
* In a big organisation, helps disambiguate more clearly between people sharing the same first name.
* From active directory I am sent the full name as text and there's no reliable method for cross-culturally figuring out what the first given name is from text, e.g. 沈马修 could be transliterated as "shen maxiu" or "shen ma xiu" and even if you use Western ordering "ma xiu shen" (often but not guaranteed to be the case when put into cross-culture systems like MSF AD), then if I was to split on spaces I would get just "ma" which is incorrect. 

> In the body email, here should be the hyperlink to the event and not the link visible.

As previously discussed this is impossible technically (see
https://stackoverflow.com/questions/5620324/mailto-link-with-html-body ) and also noting per our previous discussions that the link will be formatted as a hyperlink in the recipient's email client.

> BUG: Once I subscribe and unsubscribe it removes even the other subscribers on the display, but still in the database as there remain in the recipients for the email to be sent.
Videos sent by WhatApps to MB.

Noted, thanks for sending the videos via whatsapp.

**Comment by LucieGueuning** [comment]
See comment in the message up

**Comment by mehrdadgit** [comment]
Sending invite-to-subscribe emails now done; supporting sending invitation to multiple users.
 Note @matthewberryman I tested with mock AD user data and it worked fine :) please test with real AD logins and let me know if any issue.

**Comment by LucieGueuning** [comment]
1. ![image](https://user-images.githubusercontent.com/25951555/48433611-6cf23980-e76f-11e8-872c-aa0525f0d853.png)
![image](https://user-images.githubusercontent.com/25951555/48433623-77acce80-e76f-11e8-8ee1-eaff2117acb0.png)


- we didn't receive email for invitation
- we don't want to send email to invite, but we want to add subscribers to the list on the left. 

2. Not name yet, still email address: 
![image](https://user-images.githubusercontent.com/25951555/48433697-afb41180-e76f-11e8-992f-1de11edbba41.png)

**Comment by matthewberryman** [comment]
“

  *   we don't want to send email to invite, but we want to add subscribers to the list on the left.”

As I have indicated several times in discussions and on my latest email we will not be implementing it the way you want as it breaks double opt in best practice, so will remain as is.

We’ll review the rest.

Sent from my iPhone

On 14 Nov 2018, at 05:15, Lucie Gueuning <notifications@github.com<mailto:notifications@github.com>> wrote:

we don't want to send email to invite, but we want to add subscribers to the list on the left.

**Comment by matthewberryman** [comment]
> we didn't receive email for invitation

This should now be fixed. If not, I have added some extra logging to help me debug my end (since I can't test directly).

> we don't want to send email to invite, but we want to add subscribers to the list on the left

won't implement, breaks double opt in

> Not name yet, still email address

Fixed this display side. I'd like to do a deeper fix in extension but this should suffice for now and I have tested.

**Comment by LucieGueuning** [comment]
1. Now, I don't have suggestions from Address book coming in: 
![image](https://user-images.githubusercontent.com/25951555/48486815-72ee2600-e814-11e8-92c8-9bf254b415a8.png)
Also, note that you can test with the REACH test log in in the test environnement. 

2. ok

3. well noted for deeper fix. Thanks for sharing and your transparency.

**Comment by matthewberryman** [comment]
Re 1.: Are you logged in as test user or yourself? Test user doesn’t have permissions on AD server to do this search of directory. If you’re logged in as yourself and still have this issue then something likely got broken when I did a code merge of dev in and I will check in the morning my time.

Sent from my iPhone

On 15 Nov 2018, at 00:53, Lucie Gueuning <notifications@github.com<mailto:notifications@github.com>> wrote:


  1.  Now, I don't have suggestions from Address book coming in:
[image]<https://user-images.githubusercontent.com/25951555/48486815-72ee2600-e814-11e8-92c8-9bf254b415a8.png>
Also, note that you can test with the REACH test log in in the test environnement.

  2.  ok

  3.  well noted for deeper fix. Thanks for sharing and your transparency.

**Comment by LucieGueuning** [comment]
For viewer, instead of waiting for results, as it seems to be coming up soon as there is the load icon turning, please add the red sentences for viewers. 

For operators, 
1. possible to have the list of people having received an invitation to subscribe to an event? 

2. Having the double confirmation, as you were about to delete something, to ask people to subscribe to an event: You are about to send an email to your colleagues. Would you like to proceed? (because nobody will confident with that as it is automated). They would prefer if they have the control on the content of the email. This is the reasons : send an update to the people you have been adding yourself would make more sense. To be discussed on Thursday morning (GMT time). 

3. email wordings: 
- please remove space between Kind regards et MSF Reach. 
- MSF REACH in capital letter
- Picture not loading

![image](https://user-images.githubusercontent.com/25951555/48501196-8d37fc00-e834-11e8-8689-385b1f0735a7.png)

**Comment by matthewberryman** [comment]
@mehrdadgit since there are now only manual emails (via "send an update" button) let's go with direct subscription of another user (via a chooser like for private contact sharing with button) rather than sending an invite. We can revisit double opt in if we later move back to having automated update emails. That said, keep the current subscribe button (but I guess name that one "subscribe yourself" vs "subscribe others" for the new one), so that someone can subscribe themself directly if they want.

**Comment by matthewberryman** [comment]
the subscribe others button and email subscribers for updates button should be only viewable & usable if user has operator access #432 
but the subscribe yourself button should be viewable (and usable) by anyone

**Comment by mehrdadgit** [comment]
Ok @matthewberryman I will take care of this.

**Comment by mehrdadgit** [comment]
Done on issues/174 branch needs operator with write permission for testing.
