### ISSUE TITLE
On event page, contact info

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#82]
Can we have at a first glance : 
1. Name
2. Email
3. Phone Number
4. Affiliation

Also, contacts table need to be linked to contacts on map, on event page

**Comment by matthewberryman** [comment]
I'm still playing with the contacts table size in relation to contacts map on the events page (already tracked in other separate issues). I am not entirely sure what you mean by contacts table needs to be linked to contacts on map. You mean if you select a contact on the table it zooms to and highlights the contact on the map?

**Comment by LucieGueuning** [comment]
No I mean when event is created, the contact shown on table are the only one located nearby the disaster theater and shown the same contact on map. Do you better understand?

**Comment by clgeros** [comment]
Just to clarify Lucie's point, she's looking for a location filter... i.e. airbnb... contacts shown in table should match those visible in the map view at any given point in time.

**Comment by matthewberryman** [comment]
Gotcha. We'd already planned on that in https://github.com/usergroupcoop/msf-reach/issues/33 - but requires fairly major changes behind the scenes in the server API. Just deploying some changes now to get more contacts info in on the table.

**Comment by matthewberryman** [comment]
@LucieGueuning The work for this has broken the ability to add map controls for contacts and missions on the events, but not landing page. If you try and add the controls, then every time the map changes it adds a new contacts / missions control checkmark, resulting in a growing number over time. I've tried various fixes but strongly doubt I'll get time by the P1 milestone to fix this—I think it's a limitation of the library we're using, so possibly a full week's work just to fix this issue. @talltom can you have a look just in case I'm missing something? Do a find all on all js files for "broken" (without quotes).

**Comment by LucieGueuning** [comment]
Not sure I understand what is the issue for that.

**Comment by matthewberryman** [comment]
@LucieGueuning previously on the events page we had the ability to turn off the contacts and mission history display through the control. I have disabled that ability for now, as the work on this issue means that if you do try and display the controls, they duplicate over time. It ends up looking like this:
<img width="95" alt="screen shot 2017-10-12 at 3 03 37 pm" src="https://user-images.githubusercontent.com/2288238/31483354-9d2943c6-aef1-11e7-97cf-45877b893ccb.png">

**Comment by LucieGueuning** [comment]
now it is resolved, right?

**Comment by matthewberryman** [comment]
No, this control issue still needs to be resolved. I will look at this in the next few days unless @talltom or @mehrdadgit get a chance to look first.

**Comment by talltom** [comment]
Hi @matthewberryman - I recreated this locally but the glitch occurs only when I zoom or pan the map, can you confirm?

Also, `mapMissions()` isn't called from within the events.js module that I could see? I'm unsure how the events page is calling this function to add the missions data.

**Comment by matthewberryman** [comment]
Yes, on map zoom and pan.

Some of the js has been moved around, I can have a look when I get to my computer.

Sent from my iPhone

On 19 Oct 2017, at 07:41, Tomas Holderness <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @matthewberryman<https://github.com/matthewberryman> - I recreated this locally but the glitch occurs only when I zoom or pan the map, can you confirm?

Also, mapMissions() isn't called from within the events.js module that I could see? I'm unsure how the events page is calling this function to add the missions data.

**Comment by matthewberryman** [comment]
@talltom it's in missions.js
